In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.randn(3, 4096, 33, 33, dtype=torch.float)

In [5]:
torch.backends.cudnn.deterministic = True
torch.manual_seed(999)

conv1 = nn.Sequential(nn.Conv2d(4096, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU(),
                      nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU())


In [6]:
conv1(x)

tensor([[[[0.0000, 0.2692, 0.0000,  ..., 0.3384, 0.0000, 0.0000],
          [0.0000, 0.0524, 0.0000,  ..., 0.2224, 0.1449, 0.0000],
          [0.0000, 0.0000, 0.0827,  ..., 0.0000, 0.0000, 0.1135],
          ...,
          [0.0000, 0.6037, 0.4875,  ..., 0.7732, 0.0000, 0.4137],
          [0.0000, 0.0839, 0.4014,  ..., 0.0941, 0.0000, 0.0041],
          [0.0000, 0.2624, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0258,  ..., 0.0622, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.2217,  ..., 0.0000, 0.0264, 0.0000],
          [0.0000, 0.1538, 0.2103,  ..., 0.0778, 0.0000, 0.0669],
          ...,
          [0.0000, 0.1672, 0.3022,  ..., 0.0969, 0.0000, 0.1427],
          [0.0903, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0045, 0.0000, 0.0000]],

         [[0.0000, 0.5412, 0.7472,  ..., 0.0000, 0.0000, 0.0000],
          [0.5087, 0.0000, 0.8091,  ..., 1.6487, 0.0000, 0.7667],
          [0.2476, 0.0000, 0.0000,  ..., 0

In [7]:
torch.backends.cudnn.deterministic = True
torch.manual_seed(999)

conv2list = nn.ModuleList([nn.Conv2d(4096, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU(),
                      nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU()])

In [8]:
conv2list

ModuleList(
  (0): Conv2d(4096, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
  (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (5): ReLU()
)

In [9]:
conv2 = nn.Sequential(*conv2list)

In [10]:
conv2(x)

tensor([[[[0.0000, 0.2692, 0.0000,  ..., 0.3384, 0.0000, 0.0000],
          [0.0000, 0.0524, 0.0000,  ..., 0.2224, 0.1449, 0.0000],
          [0.0000, 0.0000, 0.0827,  ..., 0.0000, 0.0000, 0.1135],
          ...,
          [0.0000, 0.6037, 0.4875,  ..., 0.7732, 0.0000, 0.4137],
          [0.0000, 0.0839, 0.4014,  ..., 0.0941, 0.0000, 0.0041],
          [0.0000, 0.2624, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0258,  ..., 0.0622, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.2217,  ..., 0.0000, 0.0264, 0.0000],
          [0.0000, 0.1538, 0.2103,  ..., 0.0778, 0.0000, 0.0669],
          ...,
          [0.0000, 0.1672, 0.3022,  ..., 0.0969, 0.0000, 0.1427],
          [0.0903, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0045, 0.0000, 0.0000]],

         [[0.0000, 0.5412, 0.7472,  ..., 0.0000, 0.0000, 0.0000],
          [0.5087, 0.0000, 0.8091,  ..., 1.6487, 0.0000, 0.7667],
          [0.2476, 0.0000, 0.0000,  ..., 0

In [11]:
p = conv2(x)

In [33]:
drop2d = nn.Dropout2d(0.5)

In [34]:
pdrop = drop2d(p)

In [36]:
pdrop.shape

torch.Size([3, 32, 33, 33])

In [45]:
p[:,:,1,1]

tensor([[0.0524, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3380, 0.0000, 0.3262,
         0.6742, 0.0000, 0.0000, 0.0000, 0.1860, 0.2655, 0.0000, 0.0900, 0.1375,
         0.0000, 0.0000, 0.0731, 0.0000, 0.0000, 0.4844, 0.0000, 0.0000, 0.0000,
         0.0000, 0.5167, 0.0000, 0.0000, 0.0743],
        [0.0671, 0.0000, 0.0246, 0.7819, 0.1420, 0.0000, 0.1734, 0.2398, 0.0000,
         0.2715, 0.2002, 0.0270, 0.0000, 0.0000, 0.6245, 0.0000, 0.1202, 0.0000,
         0.0000, 0.0000, 0.0455, 0.0000, 0.0463, 0.0000, 0.2249, 0.3046, 0.2760,
         0.0000, 0.1834, 0.3528, 1.3424, 0.0000],
        [0.0000, 0.0000, 0.0993, 0.0000, 0.2148, 0.0000, 0.9316, 0.2573, 0.0000,
         0.0000, 0.7834, 0.1202, 0.0474, 0.1320, 0.3857, 0.5514, 0.0062, 0.5164,
         0.0000, 0.0000, 0.4761, 0.4441, 0.0039, 0.4975, 0.1260, 1.3470, 0.6010,
         0.0000, 0.0000, 0.7824, 0.0000, 0.1303]], grad_fn=<SelectBackward>)

In [46]:
pdrop[:,:,1,1]

tensor([[0.1049, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6523,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9688, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0333, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0493, 0.0000, 0.2841, 0.0000, 0.0000, 0.4796, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2405, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0927, 0.0000, 0.0000, 0.6093, 0.5521,
         0.0000, 0.3668, 0.0000, 2.6849, 0.0000],
        [0.0000, 0.0000, 0.1987, 0.0000, 0.0000, 0.0000, 1.8633, 0.5146, 0.0000,
         0.0000, 1.5667, 0.0000, 0.0000, 0.2639, 0.7714, 1.1027, 0.0124, 1.0328,
         0.0000, 0.0000, 0.9523, 0.8881, 0.0078, 0.0000, 0.2520, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<SelectBackward>)

In [47]:
 x = torch.full((2, 3, 2, 4), 1.)

In [48]:
x.shape

torch.Size([2, 3, 2, 4])

In [52]:
xdrop = drop2d(x)

In [55]:
x[0,0,:,:]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
xdrop[0,0,:,:]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
N, _, _ , _ = p.size()

In [14]:
p.view(N, -1).shape

torch.Size([3, 34848])

In [15]:
p2 = torch.flatten(p, 1)

In [16]:
p2.shape

torch.Size([3, 34848])

In [30]:
l = nn.Linear(32*33*33,1)

In [19]:
l2 = nn.Conv2d(32, 16, kernel_size=1)

In [32]:
l(p2).shape

torch.Size([3, 1])

In [20]:
l2(p).shape

torch.Size([3, 16, 33, 33])

In [37]:
l2(p)

tensor([[[[ 2.1639e-01, -1.7975e-02,  1.5701e-02,  ...,  1.2980e-01,
            2.9597e-01, -5.0215e-02],
          [ 1.7488e-01,  9.6976e-02, -2.0132e-01,  ..., -3.7243e-02,
            1.1176e-01, -4.7357e-02],
          [ 1.1665e-01,  7.1419e-04, -2.1494e-01,  ...,  1.7126e-02,
           -3.1513e-01,  2.0884e-01],
          ...,
          [ 7.5671e-02, -2.2924e-01, -5.4103e-02,  ...,  9.0692e-02,
            1.1703e-01, -9.1827e-02],
          [-1.8555e-01,  2.5177e-01, -6.8018e-02,  ..., -1.2534e-01,
           -1.3236e-01,  1.4303e-02],
          [-1.0576e-02, -1.6121e-01, -5.5170e-02,  ...,  1.6286e-01,
            5.7840e-02,  5.8851e-02]],

         [[ 5.3380e-03, -2.9567e-02, -2.1464e-01,  ..., -2.0748e-01,
           -2.9022e-02, -2.3779e-02],
          [-3.4135e-02, -2.3336e-01, -1.9029e-01,  ..., -2.4160e-02,
           -1.2347e-01, -1.9874e-01],
          [ 1.4578e-02, -2.7529e-02,  8.1546e-04,  ..., -1.3702e-01,
           -1.3030e-01, -3.4425e-02],
          ...,
     

In [29]:
p2.view(-1, 32 , 33, 33).shape

torch.Size([3, 32, 33, 33])

In [28]:
torch.eq(p2.view(3, 32 , 33, 33), p).all()

tensor(1, dtype=torch.uint8)

In [21]:
conv2listt = nn.ModuleList([nn.Conv2d(4096, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU(),
                      nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU()])

In [22]:
conv2listt

ModuleList(
  (0): Conv2d(4096, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
  (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (5): ReLU()
)

In [23]:
conv2listtt = nn.ModuleList([nn.Conv2d(4096, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU()] +
                      [nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
                      nn.BatchNorm2d(32),
                      nn.ReLU()])

In [24]:
conv2listtt

ModuleList(
  (0): Conv2d(4096, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
  (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (5): ReLU()
)

In [30]:
import numpy as np
x= np.array([[1, 0, 0, 0],
          [6, 12, 8, 4],
          [12, 24, 12, 8], 
          [24, 36, 24, 12]])

In [31]:
x.shape

(4, 4)

In [32]:
x.shape.flatten()

AttributeError: 'tuple' object has no attribute 'flatten'